version: '3'
services:
    log:
        image: log
        ports:
            - "4200:4200"            
        volumes:
            - ./://data/
        tty: true
        expose:
            - "4200"        
        stdin_open: true
        environment:
            - MODE=dev