version: '3'
services:
    migrate:
        image: vikingslog
        command: npm run migrate_run_prod
        env_file:
            - 'api/.env.prod'
    server:
        image: vikingslog
        ports:
            - "80:80"
        tty: true
        expose:
            - "80" 
        stdin_open: true
        environment:
            - MODE=dev
        command: npm run serve_prod
        env_file:
            - 'api/.env.prod'